right_arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7
  gains:
    right_arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_postion_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6
    - left_arm_joint7
  gains:
    left_arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1